# backend/docker-postgresql.yml

version: '3.8'

services:
  db:
    image: postgres:15
    container_name: groundcow-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecret
      POSTGRES_DB: groundcow
    ports:
      - "7777:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
