"""Add initial table

Revision ID: 0c0ca2db16b5
Revises:
Create Date: 2025-04-18 15:34:58.468469

"""

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = "0c0ca2db16b5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("event_created_at", sa.DateTime(), nullable=False),
        sa.Column("event_depth", sa.Float(), nullable=False),
        sa.Column(
            "event_epicenter", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("event_location", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("event_magnitude", sa.Float(), nullable=False),
        sa.Column("event_occurred_at", sa.DateTime(), nullable=False),
        sa.Column("event_source", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "event_severity",
            sa.Enum("NA", "L1", "L2", name="eventseverity"),
            nullable=False,
        ),
        sa.Column("event_is_suppressed_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_is_suppressed_by"],
            ["event.event_id"],
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_created_at", sa.DateTime(), nullable=False),
        sa.Column("user_email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "user_role",
            sa.Enum("admin", "control", "operator", name="userrole"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "zone",
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("zone_created_at", sa.DateTime(), nullable=False),
        sa.Column("zone_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("zone_note", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("zone_regions", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("zone_id"),
        sa.UniqueConstraint("zone_name"),
    )
    op.create_table(
        "alert",
        sa.Column("alert_id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=True),
        sa.Column("alert_created_at", sa.DateTime(), nullable=False),
        sa.Column("alert_alert_time", sa.DateTime(), nullable=False),
        sa.Column(
            "alert_state",
            sa.Enum("active", "resolved", "closed", name="alertstate"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["event.event_id"],
        ),
        sa.PrimaryKeyConstraint("alert_id"),
    )
    op.create_table(
        "report",
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("alert_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("report_created_at", sa.DateTime(), nullable=False),
        sa.Column("report_action_flag", sa.Boolean(), nullable=False),
        sa.Column("report_damage_flag", sa.Boolean(), nullable=False),
        sa.Column("report_factory_zone", sa.Integer(), nullable=True),
        sa.Column("report_reported_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["alert_id"],
            ["alert.alert_id"],
        ),
        sa.ForeignKeyConstraint(
            ["report_factory_zone"],
            ["zone.zone_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("report_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report")
    op.drop_table("alert")
    op.drop_table("zone")
    op.drop_table("user")
    op.drop_table("event")
    # ### end Alembic commands ###
