"""add ondelete constraints

Revision ID: 373f736c04c7
Revises: 0c0ca2db16b5
Create Date: 2025-04-19 23:53:08.580105

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "373f736c04c7"
down_revision = "0c0ca2db16b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("alert_event_id_fkey", "alert", type_="foreignkey")
    op.create_foreign_key(
        "alert_event_id_fkey",
        "alert",
        "event",
        ["event_id"],
        ["event_id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("event_event_is_suppressed_by_fkey", "event", type_="foreignkey")
    op.create_foreign_key(
        "event_event_is_suppressed_by_fkey",
        "event",
        "event",
        ["event_is_suppressed_by"],
        ["event_id"],
        ondelete="SET NULL",
    )
    op.drop_constraint("report_user_id_fkey", "report", type_="foreignkey")
    op.drop_constraint("report_report_factory_zone_fkey", "report", type_="foreignkey")
    op.drop_constraint("report_alert_id_fkey", "report", type_="foreignkey")
    op.create_foreign_key(
        "report_user_id_fkey",
        "report",
        "user",
        ["user_id"],
        ["user_id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "report_alert_id_fkey",
        "report",
        "alert",
        ["alert_id"],
        ["alert_id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "report_report_factory_zone_fkey",
        "report",
        "zone",
        ["report_factory_zone"],
        ["zone_id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("report_report_factory_zone_fkey", "report", type_="foreignkey")
    op.drop_constraint("report_alert_id_fkey", "report", type_="foreignkey")
    op.drop_constraint("report_user_id_fkey", "report", type_="foreignkey")
    op.create_foreign_key(
        "report_alert_id_fkey", "report", "alert", ["alert_id"], ["alert_id"]
    )
    op.create_foreign_key(
        "report_report_factory_zone_fkey",
        "report",
        "zone",
        ["report_factory_zone"],
        ["zone_id"],
    )
    op.create_foreign_key(
        "report_user_id_fkey", "report", "user", ["user_id"], ["user_id"]
    )
    op.drop_constraint(None, "event", type_="foreignkey")
    op.create_foreign_key(
        "event_event_is_suppressed_by_fkey",
        "event",
        "event",
        ["event_is_suppressed_by"],
        ["event_id"],
    )
    op.drop_constraint(None, "alert", type_="foreignkey")
    op.create_foreign_key(
        "alert_event_id_fkey", "alert", "event", ["event_id"], ["event_id"]
    )
    # ### end Alembic commands ###
