"""add_zone_for_user

Revision ID: 3fba3dee0a18
Revises: 7c2f98cea321
Create Date: 2025-05-26 20:23:13.937003

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3fba3dee0a18"
down_revision = "7c2f98cea321"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("zone_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "user", "zone", ["zone_id"], ["zone_id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "zone_id")
    # ### end Alembic commands ###
