"""use bigint for earthquake id

Revision ID: 5099ba781ed1
Revises: 03105556323e
Create Date: 2025-05-06 10:48:52.421408

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '5099ba781ed1'
down_revision = '03105556323e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('earthquake', 'earthquake_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('earthquake_earthquake_id_seq'::regclass)"))
    op.alter_column('event', 'earthquake_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'earthquake_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('earthquake', 'earthquake_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('earthquake_earthquake_id_seq'::regclass)"))
    # ### end Alembic commands ###
