"""add unique constraint for user email

Revision ID: 7c2f98cea321
Revises: 686a24fbec57
Create Date: 2025-05-18 01:41:29.254267

"""

from alembic import op


# revision identifiers, used by Alembic.
revision = "7c2f98cea321"
down_revision = "686a24fbec57"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user", ["user_email"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    # ### end Alembic commands ###
