// This file is auto-generated by @hey-api/openapi-ts

export type AlertCreate = {
    event_id: number;
    alert_alert_time: string;
    alert_state: AlertState;
};

export type AlertPublic = {
    event_id: number;
    alert_alert_time: string;
    alert_state: AlertState;
    alert_id: number;
    alert_created_at: string;
};

export type AlertState = 'active' | 'resolved' | 'closed';

export type AlertUpdate = {
    alert_state?: AlertState | null;
};

export type AlertsPublic = {
    data: Array<AlertPublic>;
};

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type UserCreate = {
    user_email: string;
    user_name: string;
    user_role?: UserRole;
};

export type UserPublic = {
    user_email: string;
    user_name: string;
    user_role?: UserRole;
    user_id: number;
    user_created_at: string;
};

export type UserRole = 'admin' | 'control' | 'operator';

export type UserUpdate = {
    user_email?: string | null;
    user_name?: string | null;
    user_role?: UserRole | null;
};

export type UsersPublic = {
    data: Array<UserPublic>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type ListUsersUserGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/';
};

export type ListUsersUserGetResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type ListUsersUserGetResponse = ListUsersUserGetResponses[keyof ListUsersUserGetResponses];

export type CreateUserUserPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/user/';
};

export type CreateUserUserPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserUserPostError = CreateUserUserPostErrors[keyof CreateUserUserPostErrors];

export type CreateUserUserPostResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserUserPostResponse = CreateUserUserPostResponses[keyof CreateUserUserPostResponses];

export type DeleteUserUserUserIdDeleteData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/user/{user_id}';
};

export type DeleteUserUserUserIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserUserUserIdDeleteError = DeleteUserUserUserIdDeleteErrors[keyof DeleteUserUserUserIdDeleteErrors];

export type DeleteUserUserUserIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteUserUserUserIdDeleteResponse = DeleteUserUserUserIdDeleteResponses[keyof DeleteUserUserUserIdDeleteResponses];

export type GetUserUserUserIdGetData = {
    body?: never;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/user/{user_id}';
};

export type GetUserUserUserIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserUserUserIdGetError = GetUserUserUserIdGetErrors[keyof GetUserUserUserIdGetErrors];

export type GetUserUserUserIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetUserUserUserIdGetResponse = GetUserUserUserIdGetResponses[keyof GetUserUserUserIdGetResponses];

export type UpdateUserUserUserIdPatchData = {
    body: UserUpdate;
    path: {
        user_id: number;
    };
    query?: never;
    url: '/user/{user_id}';
};

export type UpdateUserUserUserIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserUserUserIdPatchError = UpdateUserUserUserIdPatchErrors[keyof UpdateUserUserUserIdPatchErrors];

export type UpdateUserUserUserIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserUserUserIdPatchResponse = UpdateUserUserUserIdPatchResponses[keyof UpdateUserUserUserIdPatchResponses];

export type ListAlertsAlertGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/alert/';
};

export type ListAlertsAlertGetResponses = {
    /**
     * Successful Response
     */
    200: AlertsPublic;
};

export type ListAlertsAlertGetResponse = ListAlertsAlertGetResponses[keyof ListAlertsAlertGetResponses];

export type CreateAlertAlertPostData = {
    body: AlertCreate;
    path?: never;
    query?: never;
    url: '/alert/';
};

export type CreateAlertAlertPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateAlertAlertPostError = CreateAlertAlertPostErrors[keyof CreateAlertAlertPostErrors];

export type CreateAlertAlertPostResponses = {
    /**
     * Successful Response
     */
    200: AlertPublic;
};

export type CreateAlertAlertPostResponse = CreateAlertAlertPostResponses[keyof CreateAlertAlertPostResponses];

export type DeleteAlertAlertAlertIdDeleteData = {
    body?: never;
    path: {
        alert_id: number;
    };
    query?: never;
    url: '/alert/{alert_id}';
};

export type DeleteAlertAlertAlertIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteAlertAlertAlertIdDeleteError = DeleteAlertAlertAlertIdDeleteErrors[keyof DeleteAlertAlertAlertIdDeleteErrors];

export type DeleteAlertAlertAlertIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteAlertAlertAlertIdDeleteResponse = DeleteAlertAlertAlertIdDeleteResponses[keyof DeleteAlertAlertAlertIdDeleteResponses];

export type GetAlertAlertAlertIdGetData = {
    body?: never;
    path: {
        alert_id: number;
    };
    query?: never;
    url: '/alert/{alert_id}';
};

export type GetAlertAlertAlertIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAlertAlertAlertIdGetError = GetAlertAlertAlertIdGetErrors[keyof GetAlertAlertAlertIdGetErrors];

export type GetAlertAlertAlertIdGetResponses = {
    /**
     * Successful Response
     */
    200: AlertPublic;
};

export type GetAlertAlertAlertIdGetResponse = GetAlertAlertAlertIdGetResponses[keyof GetAlertAlertAlertIdGetResponses];

export type UpdateAlertAlertAlertIdPatchData = {
    body: AlertUpdate;
    path: {
        alert_id: number;
    };
    query?: never;
    url: '/alert/{alert_id}';
};

export type UpdateAlertAlertAlertIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateAlertAlertAlertIdPatchError = UpdateAlertAlertAlertIdPatchErrors[keyof UpdateAlertAlertAlertIdPatchErrors];

export type UpdateAlertAlertAlertIdPatchResponses = {
    /**
     * Successful Response
     */
    200: AlertPublic;
};

export type UpdateAlertAlertAlertIdPatchResponse = UpdateAlertAlertAlertIdPatchResponses[keyof UpdateAlertAlertAlertIdPatchResponses];

export type RootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type RootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: 'http://0.0.0.0:8000' | (string & {});
};