name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Init database
        run: |
          cd ..
          docker compose up -d

      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install dependencies
        run: |
          uv venv
          source .venv/bin/activate
          uv sync

      - name: Install test dependencies
        run: |
          source .venv/bin/activate
          uv pip install pytest pytest-cov
          
      - name: Initialize database schema
        run: |
          source .venv/bin/activate
          uv run python -c "from app.core.db import init_db; init_db()"

      - name: Run tests with coverage
        run: |
          source .venv/bin/activate
          uv run python -m pytest --cov=app app/tests/

      - name: Generate coverage report
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          source .venv/bin/activate
          uv run python -m pytest --cov=app --cov-report=xml app/tests/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./backend/coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: kiwi-rikasa/ground-cow

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run tests with coverage
        run: bun run test:coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./frontend/coverage/lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: kiwi-rikasa/ground-cow 